### ISSUE TITLE
could MS.liverK used by RNA-seq data such as TPM value?

### ISSUE THREAD

**Issue by YoungYu5** [FPetitprez/MS.liverK#1]
Hello.
I got a RNA sequencing data that contained TPM value.
I want use MS.liverK but this tool is taken only microarray data.
Can I use the program using a TPM instead of a microarray?

best.

**Comment by FPetitprez** [comment]
Hello,
The base functions of MS.liverK are designed for microarray data, but we provide a function to rescale data from other technologies. You can use the MS.liverK.convert() function as explained in the [vignette](https://github.com/FPetitprez/MS.liverK/blob/master/vignettes/vignette.pdf):
"The predictors used by MS.liverK have been optimized for data acquired using Affmetrix Human GenomeU133 Plus 2.0 Array. For data measured with other platforms, we encourage the users to convert it using the provided MS.liverK.convert function. To this end, the dataset must be already aggregated by gene, with HUGO gene symbols as row names, and samples in columns. For an optimal functionment, it is advised tohave at least 50 samples. To convert your data set, simply replace data by the name of your dataset in the following code:
MS.liverK.convert(data)"
We tested it on the TCGA LIHC dataset which is composed of RNA-seq samples, as reported in the [preprint](https://www.biorxiv.org/content/10.1101/540005v1.full).
Hope this helps!
Best,
Florent

**Comment by YoungYu5** [comment]
thanks your advice.

In MS.liverK, used HUGO gene symbols current version?
or past version at voyault paper publish data version?
best.
young

**Comment by FPetitprez** [comment]
Hi,
The HUGO gene symbol version used in the package was the one that was up to date when the package was released in  2018. But it should not have a strong impact as most gene symbols did not change. If some genes from the signatures are missing, they will simply be ignored and should not trigger an error.

**Comment by YoungYu5** [comment]
Thanks for your advice. :)
